/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTestParsersRouteImport } from './routes/_public/test-parsers'
import { Route as ApiApiExtensionFeedRouteImport } from './routes/_api/api.extension-feed'
import { Route as ApiApiFontsCjkRouteImport } from './routes/_api/api.fonts.cjk'
import { Route as ApiApiFontsFileSplatRouteImport } from './routes/_api/api.fonts.file.$'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTestParsersRoute = PublicTestParsersRouteImport.update({
  id: '/test-parsers',
  path: '/test-parsers',
  getParentRoute: () => PublicRoute,
} as any)
const ApiApiExtensionFeedRoute = ApiApiExtensionFeedRouteImport.update({
  id: '/_api/api/extension-feed',
  path: '/api/extension-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiFontsCjkRoute = ApiApiFontsCjkRouteImport.update({
  id: '/_api/api/fonts/cjk',
  path: '/api/fonts/cjk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiFontsFileSplatRoute = ApiApiFontsFileSplatRouteImport.update({
  id: '/_api/api/fonts/file/$',
  path: '/api/fonts/file/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/hello': typeof ApiHelloRoute
  '/test-parsers': typeof PublicTestParsersRoute
  '/api/extension-feed': typeof ApiApiExtensionFeedRoute
  '/api/fonts/cjk': typeof ApiApiFontsCjkRoute
  '/api/fonts/file/$': typeof ApiApiFontsFileSplatRoute
}
export interface FileRoutesByTo {
  '/hello': typeof ApiHelloRoute
  '/test-parsers': typeof PublicTestParsersRoute
  '/': typeof PublicIndexRoute
  '/api/extension-feed': typeof ApiApiExtensionFeedRoute
  '/api/fonts/cjk': typeof ApiApiFontsCjkRoute
  '/api/fonts/file/$': typeof ApiApiFontsFileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_api/hello': typeof ApiHelloRoute
  '/_public/test-parsers': typeof PublicTestParsersRoute
  '/_public/': typeof PublicIndexRoute
  '/_api/api/extension-feed': typeof ApiApiExtensionFeedRoute
  '/_api/api/fonts/cjk': typeof ApiApiFontsCjkRoute
  '/_api/api/fonts/file/$': typeof ApiApiFontsFileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hello'
    | '/test-parsers'
    | '/api/extension-feed'
    | '/api/fonts/cjk'
    | '/api/fonts/file/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hello'
    | '/test-parsers'
    | '/'
    | '/api/extension-feed'
    | '/api/fonts/cjk'
    | '/api/fonts/file/$'
  id:
    | '__root__'
    | '/_public'
    | '/_api/hello'
    | '/_public/test-parsers'
    | '/_public/'
    | '/_api/api/extension-feed'
    | '/_api/api/fonts/cjk'
    | '/_api/api/fonts/file/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  ApiHelloRoute: typeof ApiHelloRoute
  ApiApiExtensionFeedRoute: typeof ApiApiExtensionFeedRoute
  ApiApiFontsCjkRoute: typeof ApiApiFontsCjkRoute
  ApiApiFontsFileSplatRoute: typeof ApiApiFontsFileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/test-parsers': {
      id: '/_public/test-parsers'
      path: '/test-parsers'
      fullPath: '/test-parsers'
      preLoaderRoute: typeof PublicTestParsersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_api/api/extension-feed': {
      id: '/_api/api/extension-feed'
      path: '/api/extension-feed'
      fullPath: '/api/extension-feed'
      preLoaderRoute: typeof ApiApiExtensionFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/fonts/cjk': {
      id: '/_api/api/fonts/cjk'
      path: '/api/fonts/cjk'
      fullPath: '/api/fonts/cjk'
      preLoaderRoute: typeof ApiApiFontsCjkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_api/api/fonts/file/$': {
      id: '/_api/api/fonts/file/$'
      path: '/api/fonts/file/$'
      fullPath: '/api/fonts/file/$'
      preLoaderRoute: typeof ApiApiFontsFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicTestParsersRoute: typeof PublicTestParsersRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicTestParsersRoute: PublicTestParsersRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  ApiHelloRoute: ApiHelloRoute,
  ApiApiExtensionFeedRoute: ApiApiExtensionFeedRoute,
  ApiApiFontsCjkRoute: ApiApiFontsCjkRoute,
  ApiApiFontsFileSplatRoute: ApiApiFontsFileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
